apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
spec:
  replicas: 2
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - env:
        - name: DOCKER_HOST_IP
          value: 192.168.0.19
        - name: PULSAR_BROKERS
          value: pulsar://192.168.0.19:6650
        - name: REDIS_HOST
          value: 192.168.0.19:6379
        image: clmt/celte-master:latest
        name: master
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 2048m
            memory: 2048Mi
          requests:
            cpu: 1024m
            memory: 1024Mi
