# pulsar-values.yaml

# Global settings
initialize: true
image:
  repository: apachepulsar/pulsar
  tag: "3.2.0"
  pullPolicy: IfNotPresent

components:
  functions: false
  prestoCoordinator: false
  prestoWorker: false

monitoring:
  enabled: true
  prometheus:
    enabled: true

# Add this new section for the subchart
victoria-metrics-k8s-stack:
  grafana:
    enabled: true
    service:
      type: NodePort
      nodePort: 30000
    adminPassword: "eliotisthebest"
    persistence:
      enabled: true

  vmagent:
    enabled: true

  vmalert:
    enabled: false

toolset:
  enabled: false

zookeeper:
  replicaCount: 1
  resources:
    requests:
      cpu: "0.2"
      memory: "512Mi"
    limits:
      cpu: "0.5"
      memory: "1Gi"
  configData:
    PULSAR_MEM: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=128m"
  persistence:
    enabled: true
    storageClassName: "local-path"
    size: "5Gi"

bookkeeper:
  replicaCount: 1
  resources:
    requests:
      cpu: "0.2"
      memory: "512Mi"
    limits:
      cpu: "0.5"
      memory: "1Gi"
  configData:
    BOOKIE_MEM: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m"
    managedLedgerDefaultEnsembleSize: "1"
    managedLedgerDefaultWriteQuorum: "1"
    managedLedgerDefaultAckQuorum: "1"
    autoRecoveryDaemonEnabled: "true"
  persistence:
    enabled: true
    journal:
      storageClassName: "local-path"
      size: "5Gi"
    ledgers:
      storageClassName: "local-path"
      size: "10Gi"

broker:
  replicaCount: 1
  resources:
    requests:
      cpu: "0.2"
      memory: "1Gi"
    limits:
      cpu: "0.5"
      memory: "1.5Gi"
  configData:
    PULSAR_MEM: "-Xms512m -Xmx512m -XX:MaxDirectMemorySize=256m"
    managedLedgerDefaultEnsembleSize: "1"
    managedLedgerDefaultWriteQuorum: "1"
    managedLedgerDefaultAckQuorum: "1"
    loadBalancerEnabled: "false"
    brokerDeleteInactiveTopicsEnabled: "false"

proxy:
  replicaCount: 1
  resources:
    requests:
      cpu: "0.1"
      memory: "256Mi"
    limits:
      cpu: "0.2"
      memory: "512Mi"
  configData:
    PULSAR_MEM: "-Xms256m -Xmx256m -XX:MaxDirectMemorySize=128m"
    brokerServiceURL: "pulsar://pulsar-broker:6650"
    brokerWebServiceURL: "http://pulsar-broker:8080"
  service:
    type: NodePort

# NEW TOP-LEVEL CONFIGURATION FOR PUSHGATEWAY
# prometheus-pushgateway:  # This assumes the Pulsar chart can accept arbitrary top-level keys that map to subcharts if they were added as dependencies
#   enabled: true
#   service:
#     type: NodePort
#     port: 9091 # Default internal port for pushgateway
#     nodePort: 30091 # Your desired external NodePort
#   # Add any other specific pushgateway configurations here,
#   # like persistence, resources, annotations, etc.
#   # Refer to the prometheus-community/prometheus-pushgateway chart's values.yaml for options.







    # # pulsar-values.yaml

    # initialize: true

    # monitoring:
    #   enabled: false # Gardez ceci désactivé pour économiser des ressources

    # zookeeper:
    #   replicaCount: 1
    #   persistence:
    #     enabled: false

    # bookkeeper:
    #   replicaCount: 1
    #   persistence:
    #     enabled: false

    # broker:
    #   replicaCount: 1

    # proxy:
    #   replicaCount: 1
    #   service:
    #     type: NodePort # <--- CHANGEMENT ICI
    #     # Vous pouvez optionnellement spécifier les NodePorts si vous le souhaitez,
    #     # sinon Kubernetes en choisira aléatoirement dans la plage autorisée.
    #     # Exemple (décommentez et ajustez si besoin) :
    #     # ports:
    #     #   http:
    #     #     nodePort: 30080 # Pour le port HTTP 8080 du proxy
    #     #   pulsar:
    #     #     nodePort: 30650 # Pour le port binaire 6650 du proxy

    # toolset:
    #   enabled: false # Gardez ceci désactivé pour l'instant
