apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server-node
  template:
    metadata:
      labels:
        app: server-node
    spec:
      containers:
      - name: server-node
        image: clmt/celte-system:latest
        resources:
          # intial request for CPU and memory
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10