// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: systems_structs.proto
// Protobuf C++ Version: 4.25.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_systems_5fstructs_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_systems_5fstructs_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4025000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4025001 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_systems_5fstructs_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_systems_5fstructs_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_systems_5fstructs_2eproto;
namespace celte {
namespace req {
class BinaryDataPacket;
struct BinaryDataPacketDefaultTypeInternal;
extern BinaryDataPacketDefaultTypeInternal _BinaryDataPacket_default_instance_;
class ClockTick;
struct ClockTickDefaultTypeInternal;
extern ClockTickDefaultTypeInternal _ClockTick_default_instance_;
class InputUpdate;
struct InputUpdateDefaultTypeInternal;
extern InputUpdateDefaultTypeInternal _InputUpdate_default_instance_;
class RPRequest;
struct RPRequestDefaultTypeInternal;
extern RPRequestDefaultTypeInternal _RPRequest_default_instance_;
class ReplicationDataPacket;
struct ReplicationDataPacketDefaultTypeInternal;
extern ReplicationDataPacketDefaultTypeInternal _ReplicationDataPacket_default_instance_;
class SpawnPositionRequest;
struct SpawnPositionRequestDefaultTypeInternal;
extern SpawnPositionRequestDefaultTypeInternal _SpawnPositionRequest_default_instance_;
}  // namespace req
}  // namespace celte
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace celte {
namespace req {

// ===================================================================


// -------------------------------------------------------------------

class SpawnPositionRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:celte.req.SpawnPositionRequest) */ {
 public:
  inline SpawnPositionRequest() : SpawnPositionRequest(nullptr) {}
  ~SpawnPositionRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR SpawnPositionRequest(::google::protobuf::internal::ConstantInitialized);

  inline SpawnPositionRequest(const SpawnPositionRequest& from)
      : SpawnPositionRequest(nullptr, from) {}
  SpawnPositionRequest(SpawnPositionRequest&& from) noexcept
    : SpawnPositionRequest() {
    *this = ::std::move(from);
  }

  inline SpawnPositionRequest& operator=(const SpawnPositionRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SpawnPositionRequest& operator=(SpawnPositionRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SpawnPositionRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SpawnPositionRequest* internal_default_instance() {
    return reinterpret_cast<const SpawnPositionRequest*>(
               &_SpawnPositionRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SpawnPositionRequest& a, SpawnPositionRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SpawnPositionRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SpawnPositionRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SpawnPositionRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SpawnPositionRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SpawnPositionRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const SpawnPositionRequest& from) {
    SpawnPositionRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(SpawnPositionRequest* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "celte.req.SpawnPositionRequest";
  }
  protected:
  explicit SpawnPositionRequest(::google::protobuf::Arena* arena);
  SpawnPositionRequest(::google::protobuf::Arena* arena, const SpawnPositionRequest& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kClientIdFieldNumber = 1,
    kPayloadFieldNumber = 2,
  };
  // string clientId = 1;
  void clear_clientid() ;
  const std::string& clientid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_clientid(Arg_&& arg, Args_... args);
  std::string* mutable_clientid();
  PROTOBUF_NODISCARD std::string* release_clientid();
  void set_allocated_clientid(std::string* value);

  private:
  const std::string& _internal_clientid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_clientid(
      const std::string& value);
  std::string* _internal_mutable_clientid();

  public:
  // string payload = 2;
  void clear_payload() ;
  const std::string& payload() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_payload(Arg_&& arg, Args_... args);
  std::string* mutable_payload();
  PROTOBUF_NODISCARD std::string* release_payload();
  void set_allocated_payload(std::string* value);

  private:
  const std::string& _internal_payload() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_payload(
      const std::string& value);
  std::string* _internal_mutable_payload();

  public:
  // @@protoc_insertion_point(class_scope:celte.req.SpawnPositionRequest)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      54, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr clientid_;
    ::google::protobuf::internal::ArenaStringPtr payload_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_systems_5fstructs_2eproto;
};// -------------------------------------------------------------------

class ReplicationDataPacket final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:celte.req.ReplicationDataPacket) */ {
 public:
  inline ReplicationDataPacket() : ReplicationDataPacket(nullptr) {}
  ~ReplicationDataPacket() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ReplicationDataPacket(::google::protobuf::internal::ConstantInitialized);

  inline ReplicationDataPacket(const ReplicationDataPacket& from)
      : ReplicationDataPacket(nullptr, from) {}
  ReplicationDataPacket(ReplicationDataPacket&& from) noexcept
    : ReplicationDataPacket() {
    *this = ::std::move(from);
  }

  inline ReplicationDataPacket& operator=(const ReplicationDataPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReplicationDataPacket& operator=(ReplicationDataPacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ReplicationDataPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const ReplicationDataPacket* internal_default_instance() {
    return reinterpret_cast<const ReplicationDataPacket*>(
               &_ReplicationDataPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ReplicationDataPacket& a, ReplicationDataPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(ReplicationDataPacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReplicationDataPacket* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ReplicationDataPacket* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ReplicationDataPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ReplicationDataPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ReplicationDataPacket& from) {
    ReplicationDataPacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ReplicationDataPacket* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "celte.req.ReplicationDataPacket";
  }
  protected:
  explicit ReplicationDataPacket(::google::protobuf::Arena* arena);
  ReplicationDataPacket(::google::protobuf::Arena* arena, const ReplicationDataPacket& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kDataFieldNumber = 1,
  };
  // string data = 1;
  void clear_data() ;
  const std::string& data() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  std::string* mutable_data();
  PROTOBUF_NODISCARD std::string* release_data();
  void set_allocated_data(std::string* value);

  private:
  const std::string& _internal_data() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_data(
      const std::string& value);
  std::string* _internal_mutable_data();

  public:
  // @@protoc_insertion_point(class_scope:celte.req.ReplicationDataPacket)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      44, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr data_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_systems_5fstructs_2eproto;
};// -------------------------------------------------------------------

class RPRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:celte.req.RPRequest) */ {
 public:
  inline RPRequest() : RPRequest(nullptr) {}
  ~RPRequest() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR RPRequest(::google::protobuf::internal::ConstantInitialized);

  inline RPRequest(const RPRequest& from)
      : RPRequest(nullptr, from) {}
  RPRequest(RPRequest&& from) noexcept
    : RPRequest() {
    *this = ::std::move(from);
  }

  inline RPRequest& operator=(const RPRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline RPRequest& operator=(RPRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const RPRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const RPRequest* internal_default_instance() {
    return reinterpret_cast<const RPRequest*>(
               &_RPRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(RPRequest& a, RPRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(RPRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RPRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  RPRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<RPRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const RPRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const RPRequest& from) {
    RPRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(RPRequest* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "celte.req.RPRequest";
  }
  protected:
  explicit RPRequest(::google::protobuf::Arena* arena);
  RPRequest(::google::protobuf::Arena* arena, const RPRequest& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kRespondsToFieldNumber = 2,
    kResponseTopicFieldNumber = 3,
    kRpcIdFieldNumber = 4,
    kArgsFieldNumber = 5,
  };
  // string name = 1;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // string responds_to = 2;
  void clear_responds_to() ;
  const std::string& responds_to() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_responds_to(Arg_&& arg, Args_... args);
  std::string* mutable_responds_to();
  PROTOBUF_NODISCARD std::string* release_responds_to();
  void set_allocated_responds_to(std::string* value);

  private:
  const std::string& _internal_responds_to() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_responds_to(
      const std::string& value);
  std::string* _internal_mutable_responds_to();

  public:
  // string response_topic = 3;
  void clear_response_topic() ;
  const std::string& response_topic() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_response_topic(Arg_&& arg, Args_... args);
  std::string* mutable_response_topic();
  PROTOBUF_NODISCARD std::string* release_response_topic();
  void set_allocated_response_topic(std::string* value);

  private:
  const std::string& _internal_response_topic() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_response_topic(
      const std::string& value);
  std::string* _internal_mutable_response_topic();

  public:
  // string rpc_id = 4;
  void clear_rpc_id() ;
  const std::string& rpc_id() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_rpc_id(Arg_&& arg, Args_... args);
  std::string* mutable_rpc_id();
  PROTOBUF_NODISCARD std::string* release_rpc_id();
  void set_allocated_rpc_id(std::string* value);

  private:
  const std::string& _internal_rpc_id() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_rpc_id(
      const std::string& value);
  std::string* _internal_mutable_rpc_id();

  public:
  // string args = 5;
  void clear_args() ;
  const std::string& args() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_args(Arg_&& arg, Args_... args);
  std::string* mutable_args();
  PROTOBUF_NODISCARD std::string* release_args();
  void set_allocated_args(std::string* value);

  private:
  const std::string& _internal_args() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_args(
      const std::string& value);
  std::string* _internal_mutable_args();

  public:
  // @@protoc_insertion_point(class_scope:celte.req.RPRequest)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      67, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr responds_to_;
    ::google::protobuf::internal::ArenaStringPtr response_topic_;
    ::google::protobuf::internal::ArenaStringPtr rpc_id_;
    ::google::protobuf::internal::ArenaStringPtr args_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_systems_5fstructs_2eproto;
};// -------------------------------------------------------------------

class InputUpdate final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:celte.req.InputUpdate) */ {
 public:
  inline InputUpdate() : InputUpdate(nullptr) {}
  ~InputUpdate() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR InputUpdate(::google::protobuf::internal::ConstantInitialized);

  inline InputUpdate(const InputUpdate& from)
      : InputUpdate(nullptr, from) {}
  InputUpdate(InputUpdate&& from) noexcept
    : InputUpdate() {
    *this = ::std::move(from);
  }

  inline InputUpdate& operator=(const InputUpdate& from) {
    CopyFrom(from);
    return *this;
  }
  inline InputUpdate& operator=(InputUpdate&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InputUpdate& default_instance() {
    return *internal_default_instance();
  }
  static inline const InputUpdate* internal_default_instance() {
    return reinterpret_cast<const InputUpdate*>(
               &_InputUpdate_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(InputUpdate& a, InputUpdate& b) {
    a.Swap(&b);
  }
  inline void Swap(InputUpdate* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InputUpdate* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InputUpdate* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InputUpdate>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const InputUpdate& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const InputUpdate& from) {
    InputUpdate::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(InputUpdate* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "celte.req.InputUpdate";
  }
  protected:
  explicit InputUpdate(::google::protobuf::Arena* arena);
  InputUpdate(::google::protobuf::Arena* arena, const InputUpdate& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kUuidFieldNumber = 3,
    kPressedFieldNumber = 2,
    kXFieldNumber = 4,
    kYFieldNumber = 5,
  };
  // string name = 1;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // string uuid = 3;
  void clear_uuid() ;
  const std::string& uuid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_uuid(Arg_&& arg, Args_... args);
  std::string* mutable_uuid();
  PROTOBUF_NODISCARD std::string* release_uuid();
  void set_allocated_uuid(std::string* value);

  private:
  const std::string& _internal_uuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_uuid(
      const std::string& value);
  std::string* _internal_mutable_uuid();

  public:
  // bool pressed = 2;
  void clear_pressed() ;
  bool pressed() const;
  void set_pressed(bool value);

  private:
  bool _internal_pressed() const;
  void _internal_set_pressed(bool value);

  public:
  // float x = 4;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 5;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // @@protoc_insertion_point(class_scope:celte.req.InputUpdate)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      38, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr uuid_;
    bool pressed_;
    float x_;
    float y_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_systems_5fstructs_2eproto;
};// -------------------------------------------------------------------

class ClockTick final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:celte.req.ClockTick) */ {
 public:
  inline ClockTick() : ClockTick(nullptr) {}
  ~ClockTick() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR ClockTick(::google::protobuf::internal::ConstantInitialized);

  inline ClockTick(const ClockTick& from)
      : ClockTick(nullptr, from) {}
  ClockTick(ClockTick&& from) noexcept
    : ClockTick() {
    *this = ::std::move(from);
  }

  inline ClockTick& operator=(const ClockTick& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClockTick& operator=(ClockTick&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ClockTick& default_instance() {
    return *internal_default_instance();
  }
  static inline const ClockTick* internal_default_instance() {
    return reinterpret_cast<const ClockTick*>(
               &_ClockTick_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(ClockTick& a, ClockTick& b) {
    a.Swap(&b);
  }
  inline void Swap(ClockTick* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClockTick* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ClockTick* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ClockTick>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ClockTick& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const ClockTick& from) {
    ClockTick::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ClockTick* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "celte.req.ClockTick";
  }
  protected:
  explicit ClockTick(::google::protobuf::Arena* arena);
  ClockTick(::google::protobuf::Arena* arena, const ClockTick& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUnifiedTimeMsFieldNumber = 2,
  };
  // int64 unified_time_ms = 2;
  void clear_unified_time_ms() ;
  ::int64_t unified_time_ms() const;
  void set_unified_time_ms(::int64_t value);

  private:
  ::int64_t _internal_unified_time_ms() const;
  void _internal_set_unified_time_ms(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:celte.req.ClockTick)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::int64_t unified_time_ms_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_systems_5fstructs_2eproto;
};// -------------------------------------------------------------------

class BinaryDataPacket final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:celte.req.BinaryDataPacket) */ {
 public:
  inline BinaryDataPacket() : BinaryDataPacket(nullptr) {}
  ~BinaryDataPacket() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR BinaryDataPacket(::google::protobuf::internal::ConstantInitialized);

  inline BinaryDataPacket(const BinaryDataPacket& from)
      : BinaryDataPacket(nullptr, from) {}
  BinaryDataPacket(BinaryDataPacket&& from) noexcept
    : BinaryDataPacket() {
    *this = ::std::move(from);
  }

  inline BinaryDataPacket& operator=(const BinaryDataPacket& from) {
    CopyFrom(from);
    return *this;
  }
  inline BinaryDataPacket& operator=(BinaryDataPacket&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BinaryDataPacket& default_instance() {
    return *internal_default_instance();
  }
  static inline const BinaryDataPacket* internal_default_instance() {
    return reinterpret_cast<const BinaryDataPacket*>(
               &_BinaryDataPacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BinaryDataPacket& a, BinaryDataPacket& b) {
    a.Swap(&b);
  }
  inline void Swap(BinaryDataPacket* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BinaryDataPacket* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BinaryDataPacket* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BinaryDataPacket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BinaryDataPacket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const BinaryDataPacket& from) {
    BinaryDataPacket::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(BinaryDataPacket* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "celte.req.BinaryDataPacket";
  }
  protected:
  explicit BinaryDataPacket(::google::protobuf::Arena* arena);
  BinaryDataPacket(::google::protobuf::Arena* arena, const BinaryDataPacket& from);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kBinaryDataFieldNumber = 1,
    kPeerUuidFieldNumber = 2,
  };
  // string binaryData = 1;
  void clear_binarydata() ;
  const std::string& binarydata() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_binarydata(Arg_&& arg, Args_... args);
  std::string* mutable_binarydata();
  PROTOBUF_NODISCARD std::string* release_binarydata();
  void set_allocated_binarydata(std::string* value);

  private:
  const std::string& _internal_binarydata() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_binarydata(
      const std::string& value);
  std::string* _internal_mutable_binarydata();

  public:
  // string peerUuid = 2;
  void clear_peeruuid() ;
  const std::string& peeruuid() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_peeruuid(Arg_&& arg, Args_... args);
  std::string* mutable_peeruuid();
  PROTOBUF_NODISCARD std::string* release_peeruuid();
  void set_allocated_peeruuid(std::string* value);

  private:
  const std::string& _internal_peeruuid() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_peeruuid(
      const std::string& value);
  std::string* _internal_mutable_peeruuid();

  public:
  // @@protoc_insertion_point(class_scope:celte.req.BinaryDataPacket)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      53, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr binarydata_;
    ::google::protobuf::internal::ArenaStringPtr peeruuid_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_systems_5fstructs_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// BinaryDataPacket

// string binaryData = 1;
inline void BinaryDataPacket::clear_binarydata() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.binarydata_.ClearToEmpty();
}
inline const std::string& BinaryDataPacket::binarydata() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celte.req.BinaryDataPacket.binaryData)
  return _internal_binarydata();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void BinaryDataPacket::set_binarydata(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.binarydata_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:celte.req.BinaryDataPacket.binaryData)
}
inline std::string* BinaryDataPacket::mutable_binarydata() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_binarydata();
  // @@protoc_insertion_point(field_mutable:celte.req.BinaryDataPacket.binaryData)
  return _s;
}
inline const std::string& BinaryDataPacket::_internal_binarydata() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.binarydata_.Get();
}
inline void BinaryDataPacket::_internal_set_binarydata(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.binarydata_.Set(value, GetArena());
}
inline std::string* BinaryDataPacket::_internal_mutable_binarydata() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.binarydata_.Mutable( GetArena());
}
inline std::string* BinaryDataPacket::release_binarydata() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:celte.req.BinaryDataPacket.binaryData)
  return _impl_.binarydata_.Release();
}
inline void BinaryDataPacket::set_allocated_binarydata(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.binarydata_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.binarydata_.IsDefault()) {
          _impl_.binarydata_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:celte.req.BinaryDataPacket.binaryData)
}

// string peerUuid = 2;
inline void BinaryDataPacket::clear_peeruuid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.peeruuid_.ClearToEmpty();
}
inline const std::string& BinaryDataPacket::peeruuid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celte.req.BinaryDataPacket.peerUuid)
  return _internal_peeruuid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void BinaryDataPacket::set_peeruuid(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.peeruuid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:celte.req.BinaryDataPacket.peerUuid)
}
inline std::string* BinaryDataPacket::mutable_peeruuid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_peeruuid();
  // @@protoc_insertion_point(field_mutable:celte.req.BinaryDataPacket.peerUuid)
  return _s;
}
inline const std::string& BinaryDataPacket::_internal_peeruuid() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.peeruuid_.Get();
}
inline void BinaryDataPacket::_internal_set_peeruuid(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.peeruuid_.Set(value, GetArena());
}
inline std::string* BinaryDataPacket::_internal_mutable_peeruuid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.peeruuid_.Mutable( GetArena());
}
inline std::string* BinaryDataPacket::release_peeruuid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:celte.req.BinaryDataPacket.peerUuid)
  return _impl_.peeruuid_.Release();
}
inline void BinaryDataPacket::set_allocated_peeruuid(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.peeruuid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.peeruuid_.IsDefault()) {
          _impl_.peeruuid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:celte.req.BinaryDataPacket.peerUuid)
}

// -------------------------------------------------------------------

// SpawnPositionRequest

// string clientId = 1;
inline void SpawnPositionRequest::clear_clientid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.clientid_.ClearToEmpty();
}
inline const std::string& SpawnPositionRequest::clientid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celte.req.SpawnPositionRequest.clientId)
  return _internal_clientid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SpawnPositionRequest::set_clientid(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.clientid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:celte.req.SpawnPositionRequest.clientId)
}
inline std::string* SpawnPositionRequest::mutable_clientid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_clientid();
  // @@protoc_insertion_point(field_mutable:celte.req.SpawnPositionRequest.clientId)
  return _s;
}
inline const std::string& SpawnPositionRequest::_internal_clientid() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.clientid_.Get();
}
inline void SpawnPositionRequest::_internal_set_clientid(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.clientid_.Set(value, GetArena());
}
inline std::string* SpawnPositionRequest::_internal_mutable_clientid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.clientid_.Mutable( GetArena());
}
inline std::string* SpawnPositionRequest::release_clientid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:celte.req.SpawnPositionRequest.clientId)
  return _impl_.clientid_.Release();
}
inline void SpawnPositionRequest::set_allocated_clientid(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.clientid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.clientid_.IsDefault()) {
          _impl_.clientid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:celte.req.SpawnPositionRequest.clientId)
}

// string payload = 2;
inline void SpawnPositionRequest::clear_payload() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.payload_.ClearToEmpty();
}
inline const std::string& SpawnPositionRequest::payload() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celte.req.SpawnPositionRequest.payload)
  return _internal_payload();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SpawnPositionRequest::set_payload(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.payload_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:celte.req.SpawnPositionRequest.payload)
}
inline std::string* SpawnPositionRequest::mutable_payload() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_payload();
  // @@protoc_insertion_point(field_mutable:celte.req.SpawnPositionRequest.payload)
  return _s;
}
inline const std::string& SpawnPositionRequest::_internal_payload() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.payload_.Get();
}
inline void SpawnPositionRequest::_internal_set_payload(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.payload_.Set(value, GetArena());
}
inline std::string* SpawnPositionRequest::_internal_mutable_payload() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.payload_.Mutable( GetArena());
}
inline std::string* SpawnPositionRequest::release_payload() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:celte.req.SpawnPositionRequest.payload)
  return _impl_.payload_.Release();
}
inline void SpawnPositionRequest::set_allocated_payload(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.payload_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.payload_.IsDefault()) {
          _impl_.payload_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:celte.req.SpawnPositionRequest.payload)
}

// -------------------------------------------------------------------

// ReplicationDataPacket

// string data = 1;
inline void ReplicationDataPacket::clear_data() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.data_.ClearToEmpty();
}
inline const std::string& ReplicationDataPacket::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celte.req.ReplicationDataPacket.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ReplicationDataPacket::set_data(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.data_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:celte.req.ReplicationDataPacket.data)
}
inline std::string* ReplicationDataPacket::mutable_data() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:celte.req.ReplicationDataPacket.data)
  return _s;
}
inline const std::string& ReplicationDataPacket::_internal_data() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.data_.Get();
}
inline void ReplicationDataPacket::_internal_set_data(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.data_.Set(value, GetArena());
}
inline std::string* ReplicationDataPacket::_internal_mutable_data() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.data_.Mutable( GetArena());
}
inline std::string* ReplicationDataPacket::release_data() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:celte.req.ReplicationDataPacket.data)
  return _impl_.data_.Release();
}
inline void ReplicationDataPacket::set_allocated_data(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.data_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.data_.IsDefault()) {
          _impl_.data_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:celte.req.ReplicationDataPacket.data)
}

// -------------------------------------------------------------------

// InputUpdate

// string name = 1;
inline void InputUpdate::clear_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.name_.ClearToEmpty();
}
inline const std::string& InputUpdate::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celte.req.InputUpdate.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void InputUpdate::set_name(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:celte.req.InputUpdate.name)
}
inline std::string* InputUpdate::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:celte.req.InputUpdate.name)
  return _s;
}
inline const std::string& InputUpdate::_internal_name() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.name_.Get();
}
inline void InputUpdate::_internal_set_name(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.name_.Set(value, GetArena());
}
inline std::string* InputUpdate::_internal_mutable_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* InputUpdate::release_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:celte.req.InputUpdate.name)
  return _impl_.name_.Release();
}
inline void InputUpdate::set_allocated_name(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.name_.IsDefault()) {
          _impl_.name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:celte.req.InputUpdate.name)
}

// bool pressed = 2;
inline void InputUpdate::clear_pressed() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.pressed_ = false;
}
inline bool InputUpdate::pressed() const {
  // @@protoc_insertion_point(field_get:celte.req.InputUpdate.pressed)
  return _internal_pressed();
}
inline void InputUpdate::set_pressed(bool value) {
  _internal_set_pressed(value);
  // @@protoc_insertion_point(field_set:celte.req.InputUpdate.pressed)
}
inline bool InputUpdate::_internal_pressed() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.pressed_;
}
inline void InputUpdate::_internal_set_pressed(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.pressed_ = value;
}

// string uuid = 3;
inline void InputUpdate::clear_uuid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.uuid_.ClearToEmpty();
}
inline const std::string& InputUpdate::uuid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celte.req.InputUpdate.uuid)
  return _internal_uuid();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void InputUpdate::set_uuid(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.uuid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:celte.req.InputUpdate.uuid)
}
inline std::string* InputUpdate::mutable_uuid() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_uuid();
  // @@protoc_insertion_point(field_mutable:celte.req.InputUpdate.uuid)
  return _s;
}
inline const std::string& InputUpdate::_internal_uuid() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.uuid_.Get();
}
inline void InputUpdate::_internal_set_uuid(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.uuid_.Set(value, GetArena());
}
inline std::string* InputUpdate::_internal_mutable_uuid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.uuid_.Mutable( GetArena());
}
inline std::string* InputUpdate::release_uuid() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:celte.req.InputUpdate.uuid)
  return _impl_.uuid_.Release();
}
inline void InputUpdate::set_allocated_uuid(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.uuid_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.uuid_.IsDefault()) {
          _impl_.uuid_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:celte.req.InputUpdate.uuid)
}

// float x = 4;
inline void InputUpdate::clear_x() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.x_ = 0;
}
inline float InputUpdate::x() const {
  // @@protoc_insertion_point(field_get:celte.req.InputUpdate.x)
  return _internal_x();
}
inline void InputUpdate::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:celte.req.InputUpdate.x)
}
inline float InputUpdate::_internal_x() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.x_;
}
inline void InputUpdate::_internal_set_x(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.x_ = value;
}

// float y = 5;
inline void InputUpdate::clear_y() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.y_ = 0;
}
inline float InputUpdate::y() const {
  // @@protoc_insertion_point(field_get:celte.req.InputUpdate.y)
  return _internal_y();
}
inline void InputUpdate::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:celte.req.InputUpdate.y)
}
inline float InputUpdate::_internal_y() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.y_;
}
inline void InputUpdate::_internal_set_y(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.y_ = value;
}

// -------------------------------------------------------------------

// RPRequest

// string name = 1;
inline void RPRequest::clear_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.name_.ClearToEmpty();
}
inline const std::string& RPRequest::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celte.req.RPRequest.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RPRequest::set_name(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:celte.req.RPRequest.name)
}
inline std::string* RPRequest::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:celte.req.RPRequest.name)
  return _s;
}
inline const std::string& RPRequest::_internal_name() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.name_.Get();
}
inline void RPRequest::_internal_set_name(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.name_.Set(value, GetArena());
}
inline std::string* RPRequest::_internal_mutable_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* RPRequest::release_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:celte.req.RPRequest.name)
  return _impl_.name_.Release();
}
inline void RPRequest::set_allocated_name(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.name_.IsDefault()) {
          _impl_.name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:celte.req.RPRequest.name)
}

// string responds_to = 2;
inline void RPRequest::clear_responds_to() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.responds_to_.ClearToEmpty();
}
inline const std::string& RPRequest::responds_to() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celte.req.RPRequest.responds_to)
  return _internal_responds_to();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RPRequest::set_responds_to(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.responds_to_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:celte.req.RPRequest.responds_to)
}
inline std::string* RPRequest::mutable_responds_to() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_responds_to();
  // @@protoc_insertion_point(field_mutable:celte.req.RPRequest.responds_to)
  return _s;
}
inline const std::string& RPRequest::_internal_responds_to() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.responds_to_.Get();
}
inline void RPRequest::_internal_set_responds_to(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.responds_to_.Set(value, GetArena());
}
inline std::string* RPRequest::_internal_mutable_responds_to() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.responds_to_.Mutable( GetArena());
}
inline std::string* RPRequest::release_responds_to() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:celte.req.RPRequest.responds_to)
  return _impl_.responds_to_.Release();
}
inline void RPRequest::set_allocated_responds_to(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.responds_to_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.responds_to_.IsDefault()) {
          _impl_.responds_to_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:celte.req.RPRequest.responds_to)
}

// string response_topic = 3;
inline void RPRequest::clear_response_topic() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.response_topic_.ClearToEmpty();
}
inline const std::string& RPRequest::response_topic() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celte.req.RPRequest.response_topic)
  return _internal_response_topic();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RPRequest::set_response_topic(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.response_topic_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:celte.req.RPRequest.response_topic)
}
inline std::string* RPRequest::mutable_response_topic() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_response_topic();
  // @@protoc_insertion_point(field_mutable:celte.req.RPRequest.response_topic)
  return _s;
}
inline const std::string& RPRequest::_internal_response_topic() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.response_topic_.Get();
}
inline void RPRequest::_internal_set_response_topic(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.response_topic_.Set(value, GetArena());
}
inline std::string* RPRequest::_internal_mutable_response_topic() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.response_topic_.Mutable( GetArena());
}
inline std::string* RPRequest::release_response_topic() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:celte.req.RPRequest.response_topic)
  return _impl_.response_topic_.Release();
}
inline void RPRequest::set_allocated_response_topic(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.response_topic_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.response_topic_.IsDefault()) {
          _impl_.response_topic_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:celte.req.RPRequest.response_topic)
}

// string rpc_id = 4;
inline void RPRequest::clear_rpc_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.rpc_id_.ClearToEmpty();
}
inline const std::string& RPRequest::rpc_id() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celte.req.RPRequest.rpc_id)
  return _internal_rpc_id();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RPRequest::set_rpc_id(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.rpc_id_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:celte.req.RPRequest.rpc_id)
}
inline std::string* RPRequest::mutable_rpc_id() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_rpc_id();
  // @@protoc_insertion_point(field_mutable:celte.req.RPRequest.rpc_id)
  return _s;
}
inline const std::string& RPRequest::_internal_rpc_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.rpc_id_.Get();
}
inline void RPRequest::_internal_set_rpc_id(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.rpc_id_.Set(value, GetArena());
}
inline std::string* RPRequest::_internal_mutable_rpc_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.rpc_id_.Mutable( GetArena());
}
inline std::string* RPRequest::release_rpc_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:celte.req.RPRequest.rpc_id)
  return _impl_.rpc_id_.Release();
}
inline void RPRequest::set_allocated_rpc_id(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.rpc_id_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.rpc_id_.IsDefault()) {
          _impl_.rpc_id_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:celte.req.RPRequest.rpc_id)
}

// string args = 5;
inline void RPRequest::clear_args() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.args_.ClearToEmpty();
}
inline const std::string& RPRequest::args() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:celte.req.RPRequest.args)
  return _internal_args();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void RPRequest::set_args(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.args_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:celte.req.RPRequest.args)
}
inline std::string* RPRequest::mutable_args() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_args();
  // @@protoc_insertion_point(field_mutable:celte.req.RPRequest.args)
  return _s;
}
inline const std::string& RPRequest::_internal_args() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.args_.Get();
}
inline void RPRequest::_internal_set_args(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.args_.Set(value, GetArena());
}
inline std::string* RPRequest::_internal_mutable_args() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.args_.Mutable( GetArena());
}
inline std::string* RPRequest::release_args() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:celte.req.RPRequest.args)
  return _impl_.args_.Release();
}
inline void RPRequest::set_allocated_args(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.args_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.args_.IsDefault()) {
          _impl_.args_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:celte.req.RPRequest.args)
}

// -------------------------------------------------------------------

// ClockTick

// int64 unified_time_ms = 2;
inline void ClockTick::clear_unified_time_ms() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.unified_time_ms_ = ::int64_t{0};
}
inline ::int64_t ClockTick::unified_time_ms() const {
  // @@protoc_insertion_point(field_get:celte.req.ClockTick.unified_time_ms)
  return _internal_unified_time_ms();
}
inline void ClockTick::set_unified_time_ms(::int64_t value) {
  _internal_set_unified_time_ms(value);
  // @@protoc_insertion_point(field_set:celte.req.ClockTick.unified_time_ms)
}
inline ::int64_t ClockTick::_internal_unified_time_ms() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.unified_time_ms_;
}
inline void ClockTick::_internal_set_unified_time_ms(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.unified_time_ms_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace req
}  // namespace celte


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_systems_5fstructs_2eproto_2epb_2eh
