// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: systems_structs.proto

#include "systems_structs.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace celte {
namespace req {

inline constexpr SpawnPositionRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : clientid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        payload_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SpawnPositionRequest::SpawnPositionRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct SpawnPositionRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SpawnPositionRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SpawnPositionRequestDefaultTypeInternal() {}
  union {
    SpawnPositionRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SpawnPositionRequestDefaultTypeInternal _SpawnPositionRequest_default_instance_;
      template <typename>
PROTOBUF_CONSTEXPR ReplicationDataPacket_DataEntry_DoNotUse::ReplicationDataPacket_DataEntry_DoNotUse(::_pbi::ConstantInitialized) {}
struct ReplicationDataPacket_DataEntry_DoNotUseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReplicationDataPacket_DataEntry_DoNotUseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReplicationDataPacket_DataEntry_DoNotUseDefaultTypeInternal() {}
  union {
    ReplicationDataPacket_DataEntry_DoNotUse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReplicationDataPacket_DataEntry_DoNotUseDefaultTypeInternal _ReplicationDataPacket_DataEntry_DoNotUse_default_instance_;

inline constexpr RPRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        responds_to_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        response_topic_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        rpc_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        args_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR RPRequest::RPRequest(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct RPRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RPRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RPRequestDefaultTypeInternal() {}
  union {
    RPRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RPRequestDefaultTypeInternal _RPRequest_default_instance_;

inline constexpr InputUpdate::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        uuid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        pressed_{false},
        x_{0},
        y_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR InputUpdate::InputUpdate(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct InputUpdateDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InputUpdateDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~InputUpdateDefaultTypeInternal() {}
  union {
    InputUpdate _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InputUpdateDefaultTypeInternal _InputUpdate_default_instance_;

inline constexpr ClockTick::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : unified_time_ms_{::int64_t{0}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ClockTick::ClockTick(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ClockTickDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ClockTickDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ClockTickDefaultTypeInternal() {}
  union {
    ClockTick _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ClockTickDefaultTypeInternal _ClockTick_default_instance_;

inline constexpr BinaryDataPacket::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : binarydata_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        peeruuid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BinaryDataPacket::BinaryDataPacket(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct BinaryDataPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BinaryDataPacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BinaryDataPacketDefaultTypeInternal() {}
  union {
    BinaryDataPacket _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BinaryDataPacketDefaultTypeInternal _BinaryDataPacket_default_instance_;

inline constexpr ReplicationDataPacket::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : data_{},
        active_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR ReplicationDataPacket::ReplicationDataPacket(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct ReplicationDataPacketDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReplicationDataPacketDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReplicationDataPacketDefaultTypeInternal() {}
  union {
    ReplicationDataPacket _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReplicationDataPacketDefaultTypeInternal _ReplicationDataPacket_default_instance_;
}  // namespace req
}  // namespace celte
static ::_pb::Metadata file_level_metadata_systems_5fstructs_2eproto[7];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_systems_5fstructs_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_systems_5fstructs_2eproto = nullptr;
const ::uint32_t TableStruct_systems_5fstructs_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::celte::req::BinaryDataPacket, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::celte::req::BinaryDataPacket, _impl_.binarydata_),
    PROTOBUF_FIELD_OFFSET(::celte::req::BinaryDataPacket, _impl_.peeruuid_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::celte::req::SpawnPositionRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::celte::req::SpawnPositionRequest, _impl_.clientid_),
    PROTOBUF_FIELD_OFFSET(::celte::req::SpawnPositionRequest, _impl_.payload_),
    PROTOBUF_FIELD_OFFSET(::celte::req::ReplicationDataPacket_DataEntry_DoNotUse, _has_bits_),
    PROTOBUF_FIELD_OFFSET(::celte::req::ReplicationDataPacket_DataEntry_DoNotUse, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::celte::req::ReplicationDataPacket_DataEntry_DoNotUse, key_),
    PROTOBUF_FIELD_OFFSET(::celte::req::ReplicationDataPacket_DataEntry_DoNotUse, value_),
    0,
    1,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::celte::req::ReplicationDataPacket, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::celte::req::ReplicationDataPacket, _impl_.data_),
    PROTOBUF_FIELD_OFFSET(::celte::req::ReplicationDataPacket, _impl_.active_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::celte::req::InputUpdate, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::celte::req::InputUpdate, _impl_.name_),
    PROTOBUF_FIELD_OFFSET(::celte::req::InputUpdate, _impl_.pressed_),
    PROTOBUF_FIELD_OFFSET(::celte::req::InputUpdate, _impl_.uuid_),
    PROTOBUF_FIELD_OFFSET(::celte::req::InputUpdate, _impl_.x_),
    PROTOBUF_FIELD_OFFSET(::celte::req::InputUpdate, _impl_.y_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::celte::req::RPRequest, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::celte::req::RPRequest, _impl_.name_),
    PROTOBUF_FIELD_OFFSET(::celte::req::RPRequest, _impl_.responds_to_),
    PROTOBUF_FIELD_OFFSET(::celte::req::RPRequest, _impl_.response_topic_),
    PROTOBUF_FIELD_OFFSET(::celte::req::RPRequest, _impl_.rpc_id_),
    PROTOBUF_FIELD_OFFSET(::celte::req::RPRequest, _impl_.args_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::celte::req::ClockTick, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::celte::req::ClockTick, _impl_.unified_time_ms_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::celte::req::BinaryDataPacket)},
        {10, -1, -1, sizeof(::celte::req::SpawnPositionRequest)},
        {20, 30, -1, sizeof(::celte::req::ReplicationDataPacket_DataEntry_DoNotUse)},
        {32, -1, -1, sizeof(::celte::req::ReplicationDataPacket)},
        {42, -1, -1, sizeof(::celte::req::InputUpdate)},
        {55, -1, -1, sizeof(::celte::req::RPRequest)},
        {68, -1, -1, sizeof(::celte::req::ClockTick)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::celte::req::_BinaryDataPacket_default_instance_._instance,
    &::celte::req::_SpawnPositionRequest_default_instance_._instance,
    &::celte::req::_ReplicationDataPacket_DataEntry_DoNotUse_default_instance_._instance,
    &::celte::req::_ReplicationDataPacket_default_instance_._instance,
    &::celte::req::_InputUpdate_default_instance_._instance,
    &::celte::req::_RPRequest_default_instance_._instance,
    &::celte::req::_ClockTick_default_instance_._instance,
};
const char descriptor_table_protodef_systems_5fstructs_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\025systems_structs.proto\022\tcelte.req\"8\n\020Bi"
    "naryDataPacket\022\022\n\nbinaryData\030\001 \001(\t\022\020\n\010pe"
    "erUuid\030\002 \001(\t\"9\n\024SpawnPositionRequest\022\020\n\010"
    "clientId\030\001 \001(\t\022\017\n\007payload\030\002 \001(\t\"\216\001\n\025Repl"
    "icationDataPacket\0228\n\004data\030\001 \003(\0132*.celte."
    "req.ReplicationDataPacket.DataEntry\022\016\n\006a"
    "ctive\030\002 \001(\010\032+\n\tDataEntry\022\013\n\003key\030\001 \001(\t\022\r\n"
    "\005value\030\002 \001(\t:\0028\001\"P\n\013InputUpdate\022\014\n\004name\030"
    "\001 \001(\t\022\017\n\007pressed\030\002 \001(\010\022\014\n\004uuid\030\003 \001(\t\022\t\n\001"
    "x\030\004 \001(\002\022\t\n\001y\030\005 \001(\002\"d\n\tRPRequest\022\014\n\004name\030"
    "\001 \001(\t\022\023\n\013responds_to\030\002 \001(\t\022\026\n\016response_t"
    "opic\030\003 \001(\t\022\016\n\006rpc_id\030\004 \001(\t\022\014\n\004args\030\005 \001(\t"
    "\"$\n\tClockTick\022\027\n\017unified_time_ms\030\002 \001(\003b\006"
    "proto3"
};
static ::absl::once_flag descriptor_table_systems_5fstructs_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_systems_5fstructs_2eproto = {
    false,
    false,
    526,
    descriptor_table_protodef_systems_5fstructs_2eproto,
    "systems_structs.proto",
    &descriptor_table_systems_5fstructs_2eproto_once,
    nullptr,
    0,
    7,
    schemas,
    file_default_instances,
    TableStruct_systems_5fstructs_2eproto::offsets,
    file_level_metadata_systems_5fstructs_2eproto,
    file_level_enum_descriptors_systems_5fstructs_2eproto,
    file_level_service_descriptors_systems_5fstructs_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_systems_5fstructs_2eproto_getter() {
  return &descriptor_table_systems_5fstructs_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_systems_5fstructs_2eproto(&descriptor_table_systems_5fstructs_2eproto);
namespace celte {
namespace req {
// ===================================================================

class BinaryDataPacket::_Internal {
 public:
};

BinaryDataPacket::BinaryDataPacket(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:celte.req.BinaryDataPacket)
}
inline PROTOBUF_NDEBUG_INLINE BinaryDataPacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : binarydata_(arena, from.binarydata_),
        peeruuid_(arena, from.peeruuid_),
        _cached_size_{0} {}

BinaryDataPacket::BinaryDataPacket(
    ::google::protobuf::Arena* arena,
    const BinaryDataPacket& from)
    : ::google::protobuf::Message(arena) {
  BinaryDataPacket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:celte.req.BinaryDataPacket)
}
inline PROTOBUF_NDEBUG_INLINE BinaryDataPacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : binarydata_(arena),
        peeruuid_(arena),
        _cached_size_{0} {}

inline void BinaryDataPacket::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
BinaryDataPacket::~BinaryDataPacket() {
  // @@protoc_insertion_point(destructor:celte.req.BinaryDataPacket)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void BinaryDataPacket::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.binarydata_.Destroy();
  _impl_.peeruuid_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void BinaryDataPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:celte.req.BinaryDataPacket)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.binarydata_.ClearToEmpty();
  _impl_.peeruuid_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* BinaryDataPacket::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 53, 2> BinaryDataPacket::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_BinaryDataPacket_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string peerUuid = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(BinaryDataPacket, _impl_.peeruuid_)}},
    // string binaryData = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(BinaryDataPacket, _impl_.binarydata_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string binaryData = 1;
    {PROTOBUF_FIELD_OFFSET(BinaryDataPacket, _impl_.binarydata_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string peerUuid = 2;
    {PROTOBUF_FIELD_OFFSET(BinaryDataPacket, _impl_.peeruuid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\32\12\10\0\0\0\0\0"
    "celte.req.BinaryDataPacket"
    "binaryData"
    "peerUuid"
  }},
};

::uint8_t* BinaryDataPacket::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:celte.req.BinaryDataPacket)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string binaryData = 1;
  if (!this->_internal_binarydata().empty()) {
    const std::string& _s = this->_internal_binarydata();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "celte.req.BinaryDataPacket.binaryData");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string peerUuid = 2;
  if (!this->_internal_peeruuid().empty()) {
    const std::string& _s = this->_internal_peeruuid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "celte.req.BinaryDataPacket.peerUuid");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:celte.req.BinaryDataPacket)
  return target;
}

::size_t BinaryDataPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:celte.req.BinaryDataPacket)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string binaryData = 1;
  if (!this->_internal_binarydata().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_binarydata());
  }

  // string peerUuid = 2;
  if (!this->_internal_peeruuid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_peeruuid());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData BinaryDataPacket::_class_data_ = {
    BinaryDataPacket::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* BinaryDataPacket::GetClassData() const {
  return &_class_data_;
}

void BinaryDataPacket::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<BinaryDataPacket*>(&to_msg);
  auto& from = static_cast<const BinaryDataPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:celte.req.BinaryDataPacket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_binarydata().empty()) {
    _this->_internal_set_binarydata(from._internal_binarydata());
  }
  if (!from._internal_peeruuid().empty()) {
    _this->_internal_set_peeruuid(from._internal_peeruuid());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BinaryDataPacket::CopyFrom(const BinaryDataPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:celte.req.BinaryDataPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool BinaryDataPacket::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* BinaryDataPacket::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void BinaryDataPacket::InternalSwap(BinaryDataPacket* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.binarydata_, &other->_impl_.binarydata_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.peeruuid_, &other->_impl_.peeruuid_, arena);
}

::google::protobuf::Metadata BinaryDataPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_systems_5fstructs_2eproto_getter, &descriptor_table_systems_5fstructs_2eproto_once,
      file_level_metadata_systems_5fstructs_2eproto[0]);
}
// ===================================================================

class SpawnPositionRequest::_Internal {
 public:
};

SpawnPositionRequest::SpawnPositionRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:celte.req.SpawnPositionRequest)
}
inline PROTOBUF_NDEBUG_INLINE SpawnPositionRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : clientid_(arena, from.clientid_),
        payload_(arena, from.payload_),
        _cached_size_{0} {}

SpawnPositionRequest::SpawnPositionRequest(
    ::google::protobuf::Arena* arena,
    const SpawnPositionRequest& from)
    : ::google::protobuf::Message(arena) {
  SpawnPositionRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:celte.req.SpawnPositionRequest)
}
inline PROTOBUF_NDEBUG_INLINE SpawnPositionRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : clientid_(arena),
        payload_(arena),
        _cached_size_{0} {}

inline void SpawnPositionRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SpawnPositionRequest::~SpawnPositionRequest() {
  // @@protoc_insertion_point(destructor:celte.req.SpawnPositionRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void SpawnPositionRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.clientid_.Destroy();
  _impl_.payload_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void SpawnPositionRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:celte.req.SpawnPositionRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.clientid_.ClearToEmpty();
  _impl_.payload_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* SpawnPositionRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 54, 2> SpawnPositionRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_SpawnPositionRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string payload = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(SpawnPositionRequest, _impl_.payload_)}},
    // string clientId = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SpawnPositionRequest, _impl_.clientid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string clientId = 1;
    {PROTOBUF_FIELD_OFFSET(SpawnPositionRequest, _impl_.clientid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string payload = 2;
    {PROTOBUF_FIELD_OFFSET(SpawnPositionRequest, _impl_.payload_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\36\10\7\0\0\0\0\0"
    "celte.req.SpawnPositionRequest"
    "clientId"
    "payload"
  }},
};

::uint8_t* SpawnPositionRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:celte.req.SpawnPositionRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string clientId = 1;
  if (!this->_internal_clientid().empty()) {
    const std::string& _s = this->_internal_clientid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "celte.req.SpawnPositionRequest.clientId");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string payload = 2;
  if (!this->_internal_payload().empty()) {
    const std::string& _s = this->_internal_payload();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "celte.req.SpawnPositionRequest.payload");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:celte.req.SpawnPositionRequest)
  return target;
}

::size_t SpawnPositionRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:celte.req.SpawnPositionRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string clientId = 1;
  if (!this->_internal_clientid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_clientid());
  }

  // string payload = 2;
  if (!this->_internal_payload().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_payload());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData SpawnPositionRequest::_class_data_ = {
    SpawnPositionRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* SpawnPositionRequest::GetClassData() const {
  return &_class_data_;
}

void SpawnPositionRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<SpawnPositionRequest*>(&to_msg);
  auto& from = static_cast<const SpawnPositionRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:celte.req.SpawnPositionRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_clientid().empty()) {
    _this->_internal_set_clientid(from._internal_clientid());
  }
  if (!from._internal_payload().empty()) {
    _this->_internal_set_payload(from._internal_payload());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SpawnPositionRequest::CopyFrom(const SpawnPositionRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:celte.req.SpawnPositionRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool SpawnPositionRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* SpawnPositionRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void SpawnPositionRequest::InternalSwap(SpawnPositionRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.clientid_, &other->_impl_.clientid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.payload_, &other->_impl_.payload_, arena);
}

::google::protobuf::Metadata SpawnPositionRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_systems_5fstructs_2eproto_getter, &descriptor_table_systems_5fstructs_2eproto_once,
      file_level_metadata_systems_5fstructs_2eproto[1]);
}
// ===================================================================

ReplicationDataPacket_DataEntry_DoNotUse::ReplicationDataPacket_DataEntry_DoNotUse() {}
ReplicationDataPacket_DataEntry_DoNotUse::ReplicationDataPacket_DataEntry_DoNotUse(::google::protobuf::Arena* arena)
    : SuperType(arena) {}
::google::protobuf::Metadata ReplicationDataPacket_DataEntry_DoNotUse::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_systems_5fstructs_2eproto_getter, &descriptor_table_systems_5fstructs_2eproto_once,
      file_level_metadata_systems_5fstructs_2eproto[2]);
}
// ===================================================================

class ReplicationDataPacket::_Internal {
 public:
};

ReplicationDataPacket::ReplicationDataPacket(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:celte.req.ReplicationDataPacket)
}
inline PROTOBUF_NDEBUG_INLINE ReplicationDataPacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : data_{visibility, arena, from.data_},
        _cached_size_{0} {}

ReplicationDataPacket::ReplicationDataPacket(
    ::google::protobuf::Arena* arena,
    const ReplicationDataPacket& from)
    : ::google::protobuf::Message(arena) {
  ReplicationDataPacket* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.active_ = from._impl_.active_;

  // @@protoc_insertion_point(copy_constructor:celte.req.ReplicationDataPacket)
}
inline PROTOBUF_NDEBUG_INLINE ReplicationDataPacket::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : data_{visibility, arena},
        _cached_size_{0} {}

inline void ReplicationDataPacket::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.active_ = {};
}
ReplicationDataPacket::~ReplicationDataPacket() {
  // @@protoc_insertion_point(destructor:celte.req.ReplicationDataPacket)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ReplicationDataPacket::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ReplicationDataPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:celte.req.ReplicationDataPacket)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.data_.Clear();
  _impl_.active_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ReplicationDataPacket::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 2, 1, 44, 2> ReplicationDataPacket::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_ReplicationDataPacket_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool active = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ReplicationDataPacket, _impl_.active_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ReplicationDataPacket, _impl_.active_)}},
  }}, {{
    65535, 65535
  }}, {{
    // map<string, string> data = 1;
    {PROTOBUF_FIELD_OFFSET(ReplicationDataPacket, _impl_.data_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
    // bool active = 2;
    {PROTOBUF_FIELD_OFFSET(ReplicationDataPacket, _impl_.active_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }}, {{
    {::_pbi::TcParser::GetMapAuxInfo<
        decltype(ReplicationDataPacket()._impl_.data_)>(
        1, 0, 0, 9,
        9)},
  }}, {{
    "\37\4\0\0\0\0\0\0"
    "celte.req.ReplicationDataPacket"
    "data"
  }},
};

::uint8_t* ReplicationDataPacket::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:celte.req.ReplicationDataPacket)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // map<string, string> data = 1;
  if (!_internal_data().empty()) {
    using MapType = ::google::protobuf::Map<std::string, std::string>;
    using WireHelper = _pbi::MapEntryFuncs<std::string, std::string,
                                   _pbi::WireFormatLite::TYPE_STRING,
                                   _pbi::WireFormatLite::TYPE_STRING>;
    const auto& field = _internal_data();

    if (stream->IsSerializationDeterministic() && field.size() > 1) {
      for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "celte.req.ReplicationDataPacket.data");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "celte.req.ReplicationDataPacket.data");
      }
    } else {
      for (const auto& entry : field) {
        target = WireHelper::InternalSerialize(
            1, entry.first, entry.second, target, stream);
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "celte.req.ReplicationDataPacket.data");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "celte.req.ReplicationDataPacket.data");
      }
    }
  }

  // bool active = 2;
  if (this->_internal_active() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_active(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:celte.req.ReplicationDataPacket)
  return target;
}

::size_t ReplicationDataPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:celte.req.ReplicationDataPacket)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, string> data = 1;
  total_size += 1 * ::google::protobuf::internal::FromIntSize(_internal_data_size());
  for (const auto& entry : _internal_data()) {
    total_size += _pbi::MapEntryFuncs<std::string, std::string,
                                   _pbi::WireFormatLite::TYPE_STRING,
                                   _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
  }
  // bool active = 2;
  if (this->_internal_active() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ReplicationDataPacket::_class_data_ = {
    ReplicationDataPacket::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ReplicationDataPacket::GetClassData() const {
  return &_class_data_;
}

void ReplicationDataPacket::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ReplicationDataPacket*>(&to_msg);
  auto& from = static_cast<const ReplicationDataPacket&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:celte.req.ReplicationDataPacket)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.data_.MergeFrom(from._impl_.data_);
  if (from._internal_active() != 0) {
    _this->_internal_set_active(from._internal_active());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ReplicationDataPacket::CopyFrom(const ReplicationDataPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:celte.req.ReplicationDataPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ReplicationDataPacket::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ReplicationDataPacket::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ReplicationDataPacket::InternalSwap(ReplicationDataPacket* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.data_.InternalSwap(&other->_impl_.data_);
        swap(_impl_.active_, other->_impl_.active_);
}

::google::protobuf::Metadata ReplicationDataPacket::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_systems_5fstructs_2eproto_getter, &descriptor_table_systems_5fstructs_2eproto_once,
      file_level_metadata_systems_5fstructs_2eproto[3]);
}
// ===================================================================

class InputUpdate::_Internal {
 public:
};

InputUpdate::InputUpdate(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:celte.req.InputUpdate)
}
inline PROTOBUF_NDEBUG_INLINE InputUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        uuid_(arena, from.uuid_),
        _cached_size_{0} {}

InputUpdate::InputUpdate(
    ::google::protobuf::Arena* arena,
    const InputUpdate& from)
    : ::google::protobuf::Message(arena) {
  InputUpdate* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pressed_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, pressed_),
           offsetof(Impl_, y_) -
               offsetof(Impl_, pressed_) +
               sizeof(Impl_::y_));

  // @@protoc_insertion_point(copy_constructor:celte.req.InputUpdate)
}
inline PROTOBUF_NDEBUG_INLINE InputUpdate::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        uuid_(arena),
        _cached_size_{0} {}

inline void InputUpdate::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, pressed_),
           0,
           offsetof(Impl_, y_) -
               offsetof(Impl_, pressed_) +
               sizeof(Impl_::y_));
}
InputUpdate::~InputUpdate() {
  // @@protoc_insertion_point(destructor:celte.req.InputUpdate)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void InputUpdate::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.uuid_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void InputUpdate::Clear() {
// @@protoc_insertion_point(message_clear_start:celte.req.InputUpdate)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.uuid_.ClearToEmpty();
  ::memset(&_impl_.pressed_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.y_) -
      reinterpret_cast<char*>(&_impl_.pressed_)) + sizeof(_impl_.y_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* InputUpdate::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 38, 2> InputUpdate::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_InputUpdate_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(InputUpdate, _impl_.name_)}},
    // bool pressed = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(InputUpdate, _impl_.pressed_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(InputUpdate, _impl_.pressed_)}},
    // string uuid = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(InputUpdate, _impl_.uuid_)}},
    // float x = 4;
    {::_pbi::TcParser::FastF32S1,
     {37, 63, 0, PROTOBUF_FIELD_OFFSET(InputUpdate, _impl_.x_)}},
    // float y = 5;
    {::_pbi::TcParser::FastF32S1,
     {45, 63, 0, PROTOBUF_FIELD_OFFSET(InputUpdate, _impl_.y_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(InputUpdate, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bool pressed = 2;
    {PROTOBUF_FIELD_OFFSET(InputUpdate, _impl_.pressed_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
    // string uuid = 3;
    {PROTOBUF_FIELD_OFFSET(InputUpdate, _impl_.uuid_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float x = 4;
    {PROTOBUF_FIELD_OFFSET(InputUpdate, _impl_.x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
    // float y = 5;
    {PROTOBUF_FIELD_OFFSET(InputUpdate, _impl_.y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
    "\25\4\0\4\0\0\0\0"
    "celte.req.InputUpdate"
    "name"
    "uuid"
  }},
};

::uint8_t* InputUpdate::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:celte.req.InputUpdate)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "celte.req.InputUpdate.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // bool pressed = 2;
  if (this->_internal_pressed() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        2, this->_internal_pressed(), target);
  }

  // string uuid = 3;
  if (!this->_internal_uuid().empty()) {
    const std::string& _s = this->_internal_uuid();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "celte.req.InputUpdate.uuid");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // float x = 4;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  ::uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        4, this->_internal_x(), target);
  }

  // float y = 5;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  ::uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        5, this->_internal_y(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:celte.req.InputUpdate)
  return target;
}

::size_t InputUpdate::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:celte.req.InputUpdate)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // string uuid = 3;
  if (!this->_internal_uuid().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_uuid());
  }

  // bool pressed = 2;
  if (this->_internal_pressed() != 0) {
    total_size += 2;
  }

  // float x = 4;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_x = this->_internal_x();
  ::uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    total_size += 5;
  }

  // float y = 5;
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_y = this->_internal_y();
  ::uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    total_size += 5;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData InputUpdate::_class_data_ = {
    InputUpdate::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* InputUpdate::GetClassData() const {
  return &_class_data_;
}

void InputUpdate::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<InputUpdate*>(&to_msg);
  auto& from = static_cast<const InputUpdate&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:celte.req.InputUpdate)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_uuid().empty()) {
    _this->_internal_set_uuid(from._internal_uuid());
  }
  if (from._internal_pressed() != 0) {
    _this->_internal_set_pressed(from._internal_pressed());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_x = from._internal_x();
  ::uint32_t raw_x;
  memcpy(&raw_x, &tmp_x, sizeof(tmp_x));
  if (raw_x != 0) {
    _this->_internal_set_x(from._internal_x());
  }
  static_assert(sizeof(::uint32_t) == sizeof(float),
                "Code assumes ::uint32_t and float are the same size.");
  float tmp_y = from._internal_y();
  ::uint32_t raw_y;
  memcpy(&raw_y, &tmp_y, sizeof(tmp_y));
  if (raw_y != 0) {
    _this->_internal_set_y(from._internal_y());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void InputUpdate::CopyFrom(const InputUpdate& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:celte.req.InputUpdate)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool InputUpdate::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* InputUpdate::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void InputUpdate::InternalSwap(InputUpdate* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.uuid_, &other->_impl_.uuid_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(InputUpdate, _impl_.y_)
      + sizeof(InputUpdate::_impl_.y_)
      - PROTOBUF_FIELD_OFFSET(InputUpdate, _impl_.pressed_)>(
          reinterpret_cast<char*>(&_impl_.pressed_),
          reinterpret_cast<char*>(&other->_impl_.pressed_));
}

::google::protobuf::Metadata InputUpdate::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_systems_5fstructs_2eproto_getter, &descriptor_table_systems_5fstructs_2eproto_once,
      file_level_metadata_systems_5fstructs_2eproto[4]);
}
// ===================================================================

class RPRequest::_Internal {
 public:
};

RPRequest::RPRequest(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:celte.req.RPRequest)
}
inline PROTOBUF_NDEBUG_INLINE RPRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        responds_to_(arena, from.responds_to_),
        response_topic_(arena, from.response_topic_),
        rpc_id_(arena, from.rpc_id_),
        args_(arena, from.args_),
        _cached_size_{0} {}

RPRequest::RPRequest(
    ::google::protobuf::Arena* arena,
    const RPRequest& from)
    : ::google::protobuf::Message(arena) {
  RPRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);

  // @@protoc_insertion_point(copy_constructor:celte.req.RPRequest)
}
inline PROTOBUF_NDEBUG_INLINE RPRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        responds_to_(arena),
        response_topic_(arena),
        rpc_id_(arena),
        args_(arena),
        _cached_size_{0} {}

inline void RPRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
RPRequest::~RPRequest() {
  // @@protoc_insertion_point(destructor:celte.req.RPRequest)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void RPRequest::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.responds_to_.Destroy();
  _impl_.response_topic_.Destroy();
  _impl_.rpc_id_.Destroy();
  _impl_.args_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void RPRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:celte.req.RPRequest)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.responds_to_.ClearToEmpty();
  _impl_.response_topic_.ClearToEmpty();
  _impl_.rpc_id_.ClearToEmpty();
  _impl_.args_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* RPRequest::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 5, 0, 67, 2> RPRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    5, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967264,  // skipmap
    offsetof(decltype(_table_), field_entries),
    5,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_RPRequest_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(RPRequest, _impl_.name_)}},
    // string responds_to = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(RPRequest, _impl_.responds_to_)}},
    // string response_topic = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(RPRequest, _impl_.response_topic_)}},
    // string rpc_id = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 63, 0, PROTOBUF_FIELD_OFFSET(RPRequest, _impl_.rpc_id_)}},
    // string args = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 63, 0, PROTOBUF_FIELD_OFFSET(RPRequest, _impl_.args_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string name = 1;
    {PROTOBUF_FIELD_OFFSET(RPRequest, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string responds_to = 2;
    {PROTOBUF_FIELD_OFFSET(RPRequest, _impl_.responds_to_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string response_topic = 3;
    {PROTOBUF_FIELD_OFFSET(RPRequest, _impl_.response_topic_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string rpc_id = 4;
    {PROTOBUF_FIELD_OFFSET(RPRequest, _impl_.rpc_id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string args = 5;
    {PROTOBUF_FIELD_OFFSET(RPRequest, _impl_.args_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\23\4\13\16\6\4\0\0"
    "celte.req.RPRequest"
    "name"
    "responds_to"
    "response_topic"
    "rpc_id"
    "args"
  }},
};

::uint8_t* RPRequest::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:celte.req.RPRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "celte.req.RPRequest.name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // string responds_to = 2;
  if (!this->_internal_responds_to().empty()) {
    const std::string& _s = this->_internal_responds_to();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "celte.req.RPRequest.responds_to");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // string response_topic = 3;
  if (!this->_internal_response_topic().empty()) {
    const std::string& _s = this->_internal_response_topic();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "celte.req.RPRequest.response_topic");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // string rpc_id = 4;
  if (!this->_internal_rpc_id().empty()) {
    const std::string& _s = this->_internal_rpc_id();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "celte.req.RPRequest.rpc_id");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // string args = 5;
  if (!this->_internal_args().empty()) {
    const std::string& _s = this->_internal_args();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "celte.req.RPRequest.args");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:celte.req.RPRequest)
  return target;
}

::size_t RPRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:celte.req.RPRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // string responds_to = 2;
  if (!this->_internal_responds_to().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_responds_to());
  }

  // string response_topic = 3;
  if (!this->_internal_response_topic().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_response_topic());
  }

  // string rpc_id = 4;
  if (!this->_internal_rpc_id().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_rpc_id());
  }

  // string args = 5;
  if (!this->_internal_args().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_args());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData RPRequest::_class_data_ = {
    RPRequest::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* RPRequest::GetClassData() const {
  return &_class_data_;
}

void RPRequest::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<RPRequest*>(&to_msg);
  auto& from = static_cast<const RPRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:celte.req.RPRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_responds_to().empty()) {
    _this->_internal_set_responds_to(from._internal_responds_to());
  }
  if (!from._internal_response_topic().empty()) {
    _this->_internal_set_response_topic(from._internal_response_topic());
  }
  if (!from._internal_rpc_id().empty()) {
    _this->_internal_set_rpc_id(from._internal_rpc_id());
  }
  if (!from._internal_args().empty()) {
    _this->_internal_set_args(from._internal_args());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void RPRequest::CopyFrom(const RPRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:celte.req.RPRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool RPRequest::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* RPRequest::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void RPRequest::InternalSwap(RPRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.responds_to_, &other->_impl_.responds_to_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.response_topic_, &other->_impl_.response_topic_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.rpc_id_, &other->_impl_.rpc_id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.args_, &other->_impl_.args_, arena);
}

::google::protobuf::Metadata RPRequest::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_systems_5fstructs_2eproto_getter, &descriptor_table_systems_5fstructs_2eproto_once,
      file_level_metadata_systems_5fstructs_2eproto[5]);
}
// ===================================================================

class ClockTick::_Internal {
 public:
};

ClockTick::ClockTick(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:celte.req.ClockTick)
}
ClockTick::ClockTick(
    ::google::protobuf::Arena* arena, const ClockTick& from)
    : ClockTick(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE ClockTick::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void ClockTick::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.unified_time_ms_ = {};
}
ClockTick::~ClockTick() {
  // @@protoc_insertion_point(destructor:celte.req.ClockTick)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void ClockTick::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_NOINLINE void ClockTick::Clear() {
// @@protoc_insertion_point(message_clear_start:celte.req.ClockTick)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.unified_time_ms_ = ::int64_t{0};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* ClockTick::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> ClockTick::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967293,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_ClockTick_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // int64 unified_time_ms = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(ClockTick, _impl_.unified_time_ms_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(ClockTick, _impl_.unified_time_ms_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int64 unified_time_ms = 2;
    {PROTOBUF_FIELD_OFFSET(ClockTick, _impl_.unified_time_ms_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt64)},
  }},
  // no aux_entries
  {{
  }},
};

::uint8_t* ClockTick::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:celte.req.ClockTick)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // int64 unified_time_ms = 2;
  if (this->_internal_unified_time_ms() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this->_internal_unified_time_ms(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:celte.req.ClockTick)
  return target;
}

::size_t ClockTick::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:celte.req.ClockTick)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int64 unified_time_ms = 2;
  if (this->_internal_unified_time_ms() != 0) {
    total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
        this->_internal_unified_time_ms());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData ClockTick::_class_data_ = {
    ClockTick::MergeImpl,
    nullptr,  // OnDemandRegisterArenaDtor
};
const ::google::protobuf::Message::ClassData* ClockTick::GetClassData() const {
  return &_class_data_;
}

void ClockTick::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<ClockTick*>(&to_msg);
  auto& from = static_cast<const ClockTick&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:celte.req.ClockTick)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_unified_time_ms() != 0) {
    _this->_internal_set_unified_time_ms(from._internal_unified_time_ms());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void ClockTick::CopyFrom(const ClockTick& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:celte.req.ClockTick)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool ClockTick::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* ClockTick::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void ClockTick::InternalSwap(ClockTick* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.unified_time_ms_, other->_impl_.unified_time_ms_);
}

::google::protobuf::Metadata ClockTick::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_systems_5fstructs_2eproto_getter, &descriptor_table_systems_5fstructs_2eproto_once,
      file_level_metadata_systems_5fstructs_2eproto[6]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace req
}  // namespace celte
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
