FROM fedora:latest

# ----------------------------- INSTALL DEPENDENCIES ----------------------------- #
RUN dnf -y update && dnf -y install \
    curl \
    gcc \
    openssl-devel \
    wget

# copy the source code
COPY . /app

# ----------------------------- INSTALL .NET SDK ----------------------------- #
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc
RUN wget https://packages.microsoft.com/config/fedora/33/prod.repo
RUN mv prod.repo /etc/yum.repos.d/microsoft-prod.repo
RUN chown root:root /etc/yum.repos.d/microsoft-prod.repo
RUN dnf check-update; \
    dnf install -y dotnet-sdk-8.0

# assign the port
EXPOSE 10000
# export CXX=g++
ENV CXX=g++

# ----------------------------- INSTALL CMake ----------------------------- #
RUN dnf -y install cmake
RUN dnf install g++ -y
RUN dnf install git boost-devel -y


# ----------------------------- BUILD AND RUN THE APPLICATION ----------------------------- #

WORKDIR /app
RUN cd /app
RUN ls -la
