networks:

  redis:
    driver: bridge

services:


### MASTER
  master1:
    build:
      context: ./master
      dockerfile: Dockerfile
    container_name: master1
    networks:
      - pulsar
      - redis
    restart: on-failure
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - PULSAR_BROKERS=${PULSAR_BROKERS}
      - DOCKER_HOST_IP=${DOCKER_HOST_IP}
    depends_on:
      - redis_master
      - redis_slave
      - sentinel
      - redisinsight
      - zookeeper
      - pulsar-init
      - bookie
      - broker


### CLOCK-SERVER
  clock-server:
    build:
      context: ./clock-server
      dockerfile: Dockerfile
    container_name: clock-server
    networks:
      - pulsar
    environment:
      - PULSAR_BROKERS=${PULSAR_BROKERS}
    restart: on-failure
    depends_on:
      - redis_master
      - redis_slave
      - sentinel
      - redisinsight
      - zookeeper
      - pulsar-init
      - bookie
      - broker


### LOBBY
  lobby:
    image: clmt/celte-lobby:latest
    environment:
      - CELTE_MASTER_HOST=${CELTE_MASTER_HOST}
      - CELTE_MASTER_PORT=1908
      - CELTE_PULSAR_HOST=${PULSAR_BROKERS}
    restart: on-failure
    depends_on:
      - redis_master
      - redis_slave
      - sentinel
      - redisinsight
      - zookeeper
### REDIS
  redis_master:
    image: redis/redis-stack:latest
    container_name: redis_master
    restart: on-failure
    networks:
      - redis
    ports:
      - '6379:6379'


  redis_slave:
    image: redis/redis-stack:latest
    container_name: redis_slave
    command: redis-server --port 6380 --replicaof redis_master 6379
    restart: on-failure
    networks:
      - redis
    ports:
      - '6380:6380'

  sentinel:
    build: ./redis/sentinel
    container_name: redis_sentinel
    restart: on-failure
    networks:
      - redis
    ports:
      - '26379:26379'
    environment:
      - SENTINEL_NAME=mysentinel
      - HOST_IP="${DOCKER_HOST_IP}"

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: on-failure
    networks:
      - redis
    ports:
      - '5540:5540'
    environment:
      - REDIS_URI=redis://redis_master:6379

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis_master:6379,local:redis_slave:6380
    networks:
      - redis
    ports:
      - "5050:8081"
    user: redis

###