global:
  scrape_interval: 15s
scrape_configs:
- job_name: pulsar
  static_configs:
  - targets:
    -  192.168.219.165:8080
- job_name: pushgateway
  static_configs:
  - targets:
    -  192.168.219.165:9091
