global:
  scrape_interval: 15s
scrape_configs:
- job_name: pulsar
  static_configs:
  - targets:
    - 172.16.106.182:8080
- job_name: prometheus
  static_configs:
  - targets:
    - 172.16.106.182:9090
