global:
  scrape_interval: 15s
scrape_configs:
- job_name: pulsar
  static_configs:
  - targets:
    - 192.168.0.63:8080
- job_name: prometheus
  static_configs:
  - targets:
    - 192.168.0.63:9090
- job_name: pushgateway
  static_configs:
  - targets:
    - pushgateway:9091
