on:
    # pull_request:
    #     branches:
    #         - main
    push

jobs:
    run-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install colorama pyyaml


# Executing: mkdir -p system/build && cd system/build && if [ -z "$(ls -A .)" ]; then cmake --preset default -G Ninja ..; fi && cmake --build . --target all
# Build step systems failed with command: mkdir -p system/build && cd system/build && if [ -z "$(ls -A .)" ]; then cmake --preset default -G Ninja ..; fi && cmake --build . --target all
# Build Failed. Exiting...
            - name: Build project
              run: |
                mkdir -p system/build
                cd system/build
                if [ -z "$(ls -A .)" ]; then
                    cmake --preset default -G Ninja ..
                fi
                cmake --build . --target all
# jobs:
#   publish:
            - uses: actions/checkout@master
            - uses: seanmiddleditch/gha-setup-ninja@master
            - run: |
                mkdir build
                cd build
                cmake -G Ninja ..

            - run: cmake --build build
            - name: Run unit tests
              run: ./automations/run --test ./automations/test_suites/basicGameTest.yaml
              continue-on-error: false

            - name: Check test results
              if: ${{ failure() }}
              run: echo "❌ Tests failed. Please check the logs for more details."

            - name: Check test results
              if: ${{ success() }}
              run: echo "✅ Tests passed successfully."